import fs from "node:fs/promises";
import path from "node:path";

import type { RepoIndex, SourceSymbol, FileIndex } from "./types.js";

/**
 * Generate the "elaborated but curated" CODEMAP.md for a repo.
 *
 * Design goals (per the heavy-user design):
 *  - 10-20 KB target, hard cap ~40 KB for very large repos
 *  - Architectural info (conventions, public APIs, subsystem layout) over
 *    structural detail (line numbers, full signatures, internals)
 *  - Drift-slow content: file paths, symbol names, kinds, 1-line purposes
 *  - Skip: line numbers, full signatures, helper methods, imports
 */
export interface CodemapInputs {
  slug: string;
  repoRoot: string;
  index: RepoIndex;
  purpose?: string;
  tech?: string;
  consumes?: string[];
  consumedBy?: string[];
  conventions?: string;        // free-text user-provided conventions section
  generatedAtMs?: number;
}

export async function generateCodemap(inputs: CodemapInputs): Promise<string> {
  const {
    slug,
    repoRoot,
    index,
    purpose,
    tech,
    consumes,
    consumedBy,
    conventions,
    generatedAtMs,
  } = inputs;

  const ts = new Date(generatedAtMs ?? Date.now()).toISOString();
  const out: string[] = [];

  out.push(`# CODEMAP: ${slug}`);
  out.push("");
  out.push(
    `> Auto-generated by codemap. Edit conventions in \`${path.join(repoRoot, ".codemap-conventions.md")}\` to persist them across regenerations. See \`~/.codemaps/REGISTRY.md\` for the cross-repo list.`,
  );
  out.push("");
  out.push(`_Last generated: ${ts}_`);
  out.push("");

  // ---- Architecture
  if (purpose || tech) {
    out.push("## Architecture");
    if (tech) out.push(`- ${tech}`);
    if (purpose) {
      for (const line of purpose.split(/\r?\n/).map((l) => l.trim()).filter(Boolean)) {
        out.push(`- ${line}`);
      }
    }
    if (consumes && consumes.length) {
      out.push(`- Consumes: ${consumes.join(", ")}`);
    }
    if (consumedBy && consumedBy.length) {
      out.push(`- Consumed by: ${consumedBy.join(", ")}`);
    }
    out.push("");
  }

  // ---- Conventions
  if (conventions && conventions.trim().length > 0) {
    out.push("## Conventions");
    out.push(conventions.trim());
    out.push("");
  }

  // ---- Subsystems (grouped by top-level directory)
  out.push("## Subsystems");
  out.push("");

  const grouped = groupBySubsystem(index);
  const subsystemNames = [...grouped.keys()].sort();

  for (const subsystem of subsystemNames) {
    const files = grouped.get(subsystem)!;
    const subsystemPurpose = inferSubsystemPurpose(subsystem, files);
    out.push(`### ${subsystem}`);
    if (subsystemPurpose) {
      out.push(subsystemPurpose);
    }
    out.push("");

    // Sort files within subsystem
    const sortedFiles = [...files].sort((a, b) =>
      a.path.localeCompare(b.path),
    );

    for (const fi of sortedFiles) {
      out.push(renderFileEntry(fi));
    }
    out.push("");
  }

  // ---- Footer
  out.push("---");
  out.push(
    `_${index.files.size} files indexed. Use \`codemap find <name>\` or \`codemap read <file> <symbol>\` for symbol-level lookups._`,
  );

  return out.join("\n") + "\n";
}

function groupBySubsystem(index: RepoIndex): Map<string, FileIndex[]> {
  const groups = new Map<string, FileIndex[]>();
  for (const fi of index.files.values()) {
    const subsystem = topLevelOf(fi.path);
    const list = groups.get(subsystem);
    if (list) list.push(fi);
    else groups.set(subsystem, [fi]);
  }
  return groups;
}

function topLevelOf(relPath: string): string {
  const parts = relPath.split("/");
  if (parts.length <= 1) return "(root)";
  // Common project root → use the first two segments to give meaningful groups
  // (e.g. src/auth, src/routes) rather than collapsing everything under "src".
  if (parts[0] === "src" || parts[0] === "lib" || parts[0] === "app") {
    return parts.length >= 2 ? `${parts[0]}/${parts[1]}` : parts[0]!;
  }
  return parts[0]!;
}

function inferSubsystemPurpose(
  _subsystem: string,
  _files: FileIndex[],
): string | undefined {
  // Placeholder for v1. A future improvement: read a per-subsystem
  // .codemap-purpose.md if present, or LLM-summarize.
  return undefined;
}

function pickFileDocComment(fi: FileIndex): string | undefined {
  // Best-effort: use the doc comment of the first exported symbol as the
  // file's "purpose" hint. Most files have one primary export.
  const exported = fi.symbols.find((s) => s.exported && s.docComment);
  if (exported?.docComment) return exported.docComment;
  const any = fi.symbols.find((s) => s.docComment);
  return any?.docComment;
}

function renderFileEntry(fi: FileIndex): string {
  const lines: string[] = [];
  const purpose = pickFileDocComment(fi);
  lines.push(`- \`${fi.path}\`${purpose ? ` — ${purpose}` : ""}`);

  // Pick the "interesting" symbols: top-level definitions only, drop helpers
  // and re-exports for clarity. Methods are shown nested under their class.
  const allTopLevel = fi.symbols
    .filter(
      (s) =>
        s.kind !== "method" &&
        s.kind !== "getter" &&
        s.kind !== "setter" &&
        s.kind !== "reexport",
    )
    .filter((s) => isWorthShowing(s));

  // Bias toward exported symbols. When the file has any exports, show
  // exports only; otherwise (purely internal module) fall back to showing
  // top-level symbols capped so we don't dump every private helper.
  const exported = allTopLevel.filter((s) => s.exported);
  const topLevel = exported.length > 0 ? exported : allTopLevel.slice(0, 5);
  const hiddenInternals =
    exported.length > 0
      ? allTopLevel.filter((s) => !s.exported).length
      : Math.max(0, allTopLevel.length - topLevel.length);

  for (const sym of topLevel) {
    lines.push(`    - ${renderSymbol(sym)}`);
    if (sym.kind === "class") {
      const members = fi.symbols.filter(
        (m) =>
          m.parent === sym.name &&
          (m.kind === "method" || m.kind === "getter" || m.kind === "setter"),
      );
      const publicMembers = members.filter(
        (m) =>
          m.modifiers?.visibility !== "private" &&
          !m.name.startsWith("_") &&
          m.name !== "constructor",
      );
      // Cap method listing — if a class has 30 methods we don't want them all.
      // Top 8 by source order is a reasonable proxy for "API surface".
      const shown = publicMembers.slice(0, 8);
      for (const m of shown) {
        lines.push(`        - ${renderMember(m)}`);
      }
      if (publicMembers.length > shown.length) {
        lines.push(
          `        - … and ${publicMembers.length - shown.length} more methods`,
        );
      }
    }
  }
  if (hiddenInternals > 0) {
    lines.push(`    - _(${hiddenInternals} internal helpers omitted)_`);
  }
  return lines.join("\n");
}

function isWorthShowing(sym: SourceSymbol): boolean {
  // Drop value consts that look like private helpers / internal data.
  // (Exported ones with ALL_CAPS names are usually public API.)
  if (sym.kind === "const" && !sym.exported) return false;
  return true;
}

function renderSymbol(sym: SourceSymbol): string {
  const kind = sym.kind;
  if (kind === "interface" || kind === "type" || kind === "enum") {
    const sig = trimSignature(sym.signature, 80);
    return `\`${sig}\`${docTail(sym)}`;
  }
  if (kind === "const") {
    return `\`const ${sym.name}\`${docTail(sym)}`;
  }
  // function / class
  return `\`${kind} ${sym.name}\`${docTail(sym)}`;
}

function renderMember(sym: SourceSymbol): string {
  const tags: string[] = [];
  if (sym.modifiers?.static) tags.push("static");
  if (sym.modifiers?.async) tags.push("async");
  if (sym.modifiers?.abstract) tags.push("abstract");
  if (sym.kind === "getter") tags.push("get");
  if (sym.kind === "setter") tags.push("set");
  const tagStr = tags.length ? ` *(${tags.join(", ")})*` : "";
  return `\`${sym.name}()\`${tagStr}${docTail(sym)}`;
}

function trimSignature(sig: string, max: number): string {
  return sig.length > max ? sig.slice(0, max - 1) + "…" : sig;
}

function docTail(sym: SourceSymbol): string {
  if (!sym.docComment) return "";
  const trimmed =
    sym.docComment.length > 100
      ? sym.docComment.slice(0, 97) + "..."
      : sym.docComment;
  return ` — ${trimmed}`;
}

/**
 * Read a per-repo conventions file if the user has created one. This lets
 * users persist conventions text that the generator preserves across regens.
 */
export async function readConventionsFile(
  repoRoot: string,
): Promise<string | undefined> {
  const candidates = [
    ".codemap-conventions.md",
    ".codemap/conventions.md",
  ];
  for (const c of candidates) {
    try {
      const text = await fs.readFile(path.join(repoRoot, c), "utf8");
      return text;
    } catch {
      // try next
    }
  }
  return undefined;
}

/**
 * If the user hasn't supplied a purpose, derive one from package.json
 * (description field) as a best-effort default.
 */
export async function derivePurposeFromPackageJson(
  repoRoot: string,
): Promise<{ purpose?: string; tech?: string }> {
  try {
    const raw = await fs.readFile(
      path.join(repoRoot, "package.json"),
      "utf8",
    );
    const pkg = JSON.parse(raw) as {
      description?: string;
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    const deps = {
      ...(pkg.dependencies ?? {}),
      ...(pkg.devDependencies ?? {}),
    };
    const techParts: string[] = [];
    if (deps["next"]) techParts.push("Next.js");
    else if (deps["react"]) techParts.push("React");
    if (deps["express"]) techParts.push("Express");
    if (deps["fastify"]) techParts.push("Fastify");
    if (deps["@nestjs/core"]) techParts.push("NestJS");
    if (deps["vite"]) techParts.push("Vite");
    if (deps["typescript"]) techParts.push("TypeScript");
    if (deps["prisma"] || deps["@prisma/client"]) techParts.push("Prisma");
    if (deps["drizzle-orm"]) techParts.push("Drizzle");
    if (deps["pg"]) techParts.push("Postgres");
    return {
      purpose: pkg.description,
      tech: techParts.length ? techParts.join(" / ") : undefined,
    };
  } catch {
    return {};
  }
}
